# Generated by Django 4.1.5 on 2023-07-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bk_eventos',
            new_name='bkt_eventos',
        ),
    ]
