# Generated by Django 4.1.5 on 2023-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_bk_eventos_bkt_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkt_eventos',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
