# Generated by Django 4.1.5 on 2023-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_bkt_eventos_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkt_eventos',
            name='empresa',
        ),
        migrations.AddField(
            model_name='acreditados_def',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acreditados_tmp',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
