# Generated by Django 4.1.5 on 2023-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_bkt_eventos_empresa_acreditados_def_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditados_def',
            name='numero_doc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acreditados_tmp',
            name='numero_doc',
            field=models.CharField(max_length=10),
        ),
    ]
