# Generated by Django 4.1.5 on 2023-07-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_acreditados_def_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='acreditados_def',
            name='evento_cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
