# Generated by Django 4.1.5 on 2023-07-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_acreditados_def_evento_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='acreditadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('evento', models.CharField(blank=True, max_length=50, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
    ]
