# Generated by Django 4.1.5 on 2023-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_acreditadorevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acreditados_def',
            name='hora',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
