# Generated by Django 4.1.5 on 2023-07-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acreditados_tmp',
            name='id_evento',
        ),
        migrations.DeleteModel(
            name='acreditados_def',
        ),
        migrations.DeleteModel(
            name='acreditados_tmp',
        ),
        migrations.DeleteModel(
            name='bk_eventos',
        ),
    ]
